[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501

[theme]
base = "light"
primaryColor = "#2c5aa0"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#111827"

[client]
caching = true
displayEnabled = true
showErrorDetails = true